services:
  coolify:
    image: coolify:latest
    pull_policy: always
    build:
      context: https://github.com/coollabsio/coolify.git
      dockerfile: ./docker/production/Dockerfile
    ports:
      - "8000:8080"
    environment:
      AUTORUN_ENABLED: false
      PUSHER_HOST: "soketi"
      PUSHER_PORT: "6001"
      PUSHER_SCHEME: "http"
      PUSHER_APP_ID: "coolify"
      PUSHER_APP_KEY: "coolify"
      PUSHER_APP_SECRET: "coolify"
    volumes:
      - dev_backups_data:/var/www/html/storage/app/backups
  postgres:
    image: postgres:15-alpine
    pull_policy: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "coolify"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "coolify"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    pull_policy: always
    ports:
      - "6379:6379"
    volumes:
      - dev_redis_data:/data
  soketi:
    image: quay.io/soketi/soketi:1.6-16-alpine
    pull_policy: always
    ports:
      - "6001:6001"
    environment:
      SOKETI_DEBUG: "false"
      SOKETI_DEFAULT_APP_ID: "coolify"
      SOKETI_DEFAULT_APP_KEY: "coolify"
      SOKETI_DEFAULT_APP_SECRET: "coolify"
  mailpit:
    image: axllent/mailpit:latest
    pull_policy: always
    container_name: coolify-mail
    ports:
      - "1025:1025"
      - "8025:8025"
  minio:
    image: minio/minio:latest
    pull_policy: always
    container_name: coolify-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    volumes:
      - dev_minio_data:/data

volumes:
  dev_backups_data:
  dev_postgres_data:
  dev_redis_data:
  dev_minio_data:

networks:
  coolify:
    name: coolify
    external: false